### ISSUE TITLE
Unable to resolve service for type `LockService`

### ISSUE THREAD

**Issue by reiito1100** [iwate/azurefunctions.middlewares.singleton#1]
@iwate 
readme に従って導入しようとしましたが、以下のエラーが発生しました。

`Unable to resolve service for type 'Iwate.AzureFunctions.Middlewares.Singleton.LockService' while attempting to activate 'Iwate.AzureFunctions.Middlewares.Singleton.SingletonMiddleware'.`

readme に LockService を DI に追加する記述が必要かと思います。

**Comment by iwate** [comment]
> I tried to deploy it according to the readme, but got the following error
> 
> Unable to resolve service for type 'Iwate.AzureFunctions.Middlewares.Singleton.LockService' while attempting to activate 'Iwate. AzureFunctions.Middlewares.Singleton.SingletonMiddleware'.
>
> I think you need to add LockService to DI in the readme.
> by DeepL

And I fix it. Thank you for your contribution! @reiito1100
